### ISSUE TITLE
作者您好，冒昧在此向您请教一个问题

### ISSUE THREAD

**Issue by yrqyrqyrq99** [miozus/CapslockMagic#1]
作者您好，很抱歉在此向您请教一个问题😂

我用 AHK 写了如下一段代码，试图实现以下功能：
短按 `;` 键（< 400 ms）时仍然执行 `;` 本身的功能，长按 `;` 超过 400 ms 则直接返回，不执行任何功能

```ahk
`;::
    KeyWait, `;, T0.4
    if(ErrorLevel) {
        ToolTip, ErrorLevel = 1
        return
    } else {
        ToolTip ErrorLevel = 0
        SendInput, {;}
    }
    return
```

我在运行该脚本后出现了下面两个问题：
1. 根据 ToolTip 的提示，短按时 ErrorLevel 为 0 没有问题，但是长按时 ErrorLevel 先显示为 1 ，但在按键抬起后立刻变为 0
2. 虽然短按时 ErrorLevel 为 0 ，但是并不能正常发送 `;` 键，而是没有任何反应。并且如果短时间内多次触发 `;` 键，会有如下所示的弹窗提示。我个人猜测是我的代码造成了递归调用，但是如果不这样写，我不知道该如何调用该按键自身😂

![img](https://pic.stackoverflow.wiki/uploadImages/218/201/174/18/2022/06/24/20/56/c9f281f7-82ac-4c46-a9e3-9462b52895df.jpg)

我尝试在您的代码中找到解决方法，但是没找到（可能是我基础不够没有发现），所以冒昧地使用 Issue 功能请教一下您，还望您可以指点一下我，万分感谢

**Comment by miozus** [comment]
```javascript
switchIME()
{
    timeInterval := 50  ; 此数值96次测试，大于50则短按稳定, 变量放函数之外可能会被污染
    if (A_TimeSincePriorHotkey > timeInterval && A_PriorKey = "RShift") {
        ToolTip
        if (hasIME() = 1) {
            Send "^{Space}"
            ToolTip "EN" ; Shift得反着提示，提示切换后的状态。
        } else {
            Send "^{Space}"
            ToolTip "中"
        }
        Sleep 1000
        ToolTip
    }
}
```
之前写过的功能，区分短按和长按，可以参考一下文章  [AHK 实现中英文输入法自由](https://zhuanlan.zhihu.com/p/411502482)
