### ISSUE TITLE
按3触发数字小键盘中的F1~F12是什么作用？

### ISSUE THREAD

**Issue by yeshiqing** [miozus/CapslockMagic#2]
按 3 触发数字小键盘中的 F1 ~ F12 是什么作用？为什么不直接按 F1 ~ F12 呢？

**Comment by miozus** [comment]
因为 60/68 键盘砍掉了 `Fn` 键。改成 `fn` （键盘边缘）+ `1~=` 来按，跨度大，需要双手配合。

所以设计成 按住 `3` + 数字键。一只手可以按。

如果软件的快捷键需要 `Fn` 键的组合，我另写函数，做成跨平台统一。（例如 /bin/plugin/impl/Debug.ahk）

![image](https://user-images.githubusercontent.com/35659194/218259560-a8298ab8-864c-4cde-b598-b0be85c28e05.png)
