### ISSUE TITLE
鼠标控制不支持 macos 对吧

### ISSUE THREAD

**Issue by mobailabs** [miozus/CapslockMagic#3]
鼠标控制不支持 macos 对吧

**Comment by miozus** [comment]
参考文档：安装 [快速上手 MacOS 版](https://miozus.github.io/CapslockMagic/#/zh-cn/quick-start-macos)

>  CapsLockMagic 已支持拓展包：
> 分号特殊符 Semicolon Pull Down Symbol
> 数字小键盘 3 Awake Digital Keyboard
> 其他基础功能，请参考开源项目 [Vonng/Capslock](https://github.com/Vonng/Capslock) ，按需导入。
